version: '2.4'

networks:
  dalixiv:
    external:
      name: dalixiv

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - cfg/app.dev.env
      - cfg/postgres.dev.env
    restart: on-failure
    networks:
      - dalixiv
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:12.1
    volumes:
      - ./vol/postgres/data:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - ./cfg/postgres.dev.env
    networks:
      - dalixiv
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=admin --dbname=main" ]
      interval: 5s
      timeout: 5s
      retries: 5
